server:
  port: 8080



spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckPath: /health
        healthCheckInterval: 10s

    gateway:
      diecovery:
        locator:
          enabled: true
      routes:
        - id: demandsupply-service
          uri: lb://demandsupply-service
          predicates:
            - Path=/**
        - id: auth-service
          uri: http://localhost:3000
          predicates:
            - Path=/**

