server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${server.port}
        healthCheckPath: /health
        healthCheckInterval: 10s

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/**

          - id: demandsupply-service
            uri: lb://demandsupply-service
            predicates:
               - Path=/demandsupply/**


